---
development:
  API_URL: http://localhost:9292/api/v1
  APP_URL: http://localhost:3000

test:
  API_URL: http://localhost:9292/api/v1
  APP_URL: http://localhost:3000

production:
  API_URL: https://howtosay-api.herokuapp.com/api/v1
  APP_URL: https://howtosay-app.herokuapp.com